name = "RandomTools"
uuid = "78b59e81-de1e-446f-8627-bdfc49d5e3a9"
authors = ["WhiffleFish <tylertronics@gmail.com>"]
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
julia = "1.8"
